In [5]:
import tensorflow as tf

In [6]:
import numpy as np
import pandas as pd

In [7]:
pd.read_csv("final.csv")

,Unnamed: 0,Innings Runs,Target Score,Chased Successfully,Wickets left,CRR,Last Five,RRR,Balls_left,Bowls_done,...,Bat Second_Afghanistan,Bat Second_Australia,Bat Second_Bangladesh,Bat Second_England,Bat Second_India,Bat Second_New Zealand,Bat Second_Pakistan,Bat Second_South Africa,Bat Second_Sri Lanka,Bat Second_West Indies
0,0,70,167,1,10,6.000000,24,10.392857,56,64,...,0,0,0,0,0,0,0,1,0,0
1,1,83,140,1,10,7.114286,34,6.107143,56,64,...,0,0,0,0,1,0,0,0,0,0
2,2,184,216,0,10,8.975610,32,64.000000,3,117,...,0,0,0,0,0,0,0,0,0,1
3,3,66,75,1,10,6.491803,38,0.830769,65,55,...,0,1,0,0,0,0,0,0,0,0
4,4,94,147,0,10,7.421053,38,6.360000,50,70,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55607,55607,85,204,0,10,7.183099,36,12.981818,55,65,...,0,0,0,0,0,0,0,1,0,0
55608,55608,122,181,0,10,7.705263,32,11.419355,31,89,...,0,0,0,0,0,0,1,0,0,0
55609,55609,163,202,0,10,9.140187,51,12.315789,19,101,...,0,1,0,0,0,0,0,0,0,0
55610,55610,86,206,1,10,9.555556,37,9.863014,72,48,...,0,0,0,0,0,0,0,1,0,0
55611,55611,24,109,1,10,3.789474,16,5.795455,88,32,...,0,0,0,0,0,0,1,0,0,0

In [8]:
df = pd.read_csv("final.csv")

In [9]:
df = df.drop('Unnamed: 0', axis = 1)
df

,Innings Runs,Target Score,Chased Successfully,Wickets left,CRR,Last Five,RRR,Balls_left,Bowls_done,Runs_remaining,...,Bat Second_Afghanistan,Bat Second_Australia,Bat Second_Bangladesh,Bat Second_England,Bat Second_India,Bat Second_New Zealand,Bat Second_Pakistan,Bat Second_South Africa,Bat Second_Sri Lanka,Bat Second_West Indies
0,70,167,1,10,6.000000,24,10.392857,56,64,97,...,0,0,0,0,0,0,0,1,0,0
1,83,140,1,10,7.114286,34,6.107143,56,64,57,...,0,0,0,0,1,0,0,0,0,0
2,184,216,0,10,8.975610,32,64.000000,3,117,32,...,0,0,0,0,0,0,0,0,0,1
3,66,75,1,10,6.491803,38,0.830769,65,55,9,...,0,1,0,0,0,0,0,0,0,0
4,94,147,0,10,7.421053,38,6.360000,50,70,53,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55607,85,204,0,10,7.183099,36,12.981818,55,65,119,...,0,0,0,0,0,0,0,1,0,0
55608,122,181,0,10,7.705263,32,11.419355,31,89,59,...,0,0,0,0,0,0,1,0,0,0
55609,163,202,0,10,9.140187,51,12.315789,19,101,39,...,0,1,0,0,0,0,0,0,0,0
55610,86,206,1,10,9.555556,37,9.863014,72,48,120,...,0,0,0,0,0,0,0,1,0,0
55611,24,109,1,10,3.789474,16,5.795455,88,32,85,...,0,0,0,0,0,0,1,0,0,0

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop('Chased Successfully', axis=1)
y = df['Chased Successfully']

In [11]:
y

0        1
1        1
2        0
3        1
4        0
        ..
55607    0
55608    0
55609    0
55610    1
55611    1
Name: Chased Successfully, Length: 55612, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
y_test

31150    0
39480    1
9197     1
4207     1
30752    0
        ..
39908    1
29532    1
14543    1
17037    1
52723    0
Name: Chased Successfully, Length: 11123, dtype: int64

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential([
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Use 'softmax' for multi-class classification
])

In [15]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
history = model.fit(X_train, y_train, epochs=50, validation_split=0.2)

Epoch 1/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7982 - loss: 0.5235 - val_accuracy: 0.7915 - val_loss: 0.4792
Epoch 2/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8421 - loss: 0.3583 - val_accuracy: 0.8602 - val_loss: 0.3116
Epoch 3/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8544 - loss: 0.3311 - val_accuracy: 0.8386 - val_loss: 0.3499
Epoch 4/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8588 - loss: 0.3174 - val_accuracy: 0.8702 - val_loss: 0.2883
Epoch 5/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8745 - loss: 0.2855 - val_accuracy: 0.8511 - val_loss: 0.3309
Epoch 6/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8781 - loss: 0.2761 - val_accuracy: 0.8749 - val_loss: 0.2758
Epoch 7/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8878 - loss: 0.2531 - val_accuracy: 0.8959 - val_loss: 0.2283
Epoch 8/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8965 - loss: 0.2312 - val_accuracy: 0.9082 - val_loss: 0.2014
Epoch 9/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9002 - loss: 0.2208 - val_accuracy: 0.9126 - val_loss: 0.1908
Epoch 10/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9128 - loss: 0.1927 - val_accuracy: 0.9299 - val_loss: 0.1679
Epoch 11/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9262 - loss: 0.1717 - val_accuracy: 0.9307 - val_loss: 0.1535
Epoch 12/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9282 - loss: 0.1644 - val_accuracy: 0.9475 - val_loss: 0.1271
Epoch 13/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9448 - loss: 0.1308 - val_accuracy: 0.9507 - val_loss: 0.1111
Epoch 14/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9517 - loss: 0.1136 - val_accuracy: 0.9582 - val_loss: 0.1043
Epoch 15/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9568 - loss: 0.1044 - val_accuracy: 0.9724 - val_loss: 0.0736
Epoch 16/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9655 - loss: 0.0886 - val_accuracy: 0.9653 - val_loss: 0.0826
Epoch 17/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9685 - loss: 0.0824 - val_accuracy: 0.9608 - val_loss: 0.0954
Epoch 18/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9714 - loss: 0.0754 - val_accuracy: 0.9785 - val_loss: 0.0561
Epoch 19/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9686 - loss: 0.0827 - val_accuracy: 0.9580 - val_loss: 0.1007
Epoch 20/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9759 - loss: 0.0628 - val_accuracy: 0.9854 - val_loss: 0.0435
Epoch 21/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9821 - loss: 0.0510 - val_accuracy: 0.9866 - val_loss: 0.0362
Epoch 22/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9825 - loss: 0.0481 - val_accuracy: 0.9793 - val_loss: 0.0609
Epoch 23/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9826 - loss: 0.0466 - val_accuracy: 0.9751 - val_loss: 0.0676
Epoch 24/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9852 - loss: 0.0424 - val_accuracy: 0.9835 - val_loss: 0.0427
Epoch 25/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9848 - loss: 0.0419 - val_accuracy: 0.9864 - val_loss: 0.0369
Epoch 26/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9816 - loss: 0.0487 - val_accuracy: 0.9920 - val_loss: 0.0249
Epoch 27/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9874 - loss: 0.0350 - val_accuracy: 0.9737 - val_loss: 0.0640
Epoch 28/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9880 - loss: 0.0322 - val_accuracy: 0.9845 - val_loss: 0.0402
Epoch 29/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9805 - loss: 0.0525 - val_accuracy: 0.9944 - val_loss: 0.0173
Epoch 30/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9894 - loss: 0.0297 - val_accuracy: 0.9878 - val_loss: 0.0344
Epoch 31/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9921 - loss: 0.0237 - val_accuracy: 0.9870 - val_loss: 0.0363
Epoch 32/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9910 - loss: 0.0249 - val_accuracy: 0.9918 - val_loss: 0.0245
Epoch 33/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9903 - loss: 0.0288 - val_accuracy: 0.9948 - val_loss: 0.0137
Epoch 34/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9907 - loss: 0.0269 - val_accuracy: 0.9937 - val_loss: 0.0168
Epoch 35/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9934 - loss: 0.0208 - val_accuracy: 0.9925 - val_loss: 0.0210
Epoch 36/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9934 - loss: 0.0192 - val_accuracy: 0.9973 - val_loss: 0.0096
Epoch 37/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9913 - loss: 0.0266 - val_accuracy: 0.9826 - val_loss: 0.0440
Epoch 38/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9901 - loss: 0.0269 - val_accuracy: 0.9956 - val_loss: 0.0128
Epoch 39/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9941 - loss: 0.0168 - val_accuracy: 0.9809 - val_loss: 0.0634
Epoch 40/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9914 - loss: 0.0260 - val_accuracy: 0.9906 - val_loss: 0.0274
Epoch 41/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9882 - loss: 0.0307 - val_accuracy: 0.9961 - val_loss: 0.0120
Epoch 42/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9949 - loss: 0.0144 - val_accuracy: 0.9973 - val_loss: 0.0093
Epoch 43/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9927 - loss: 0.0204 - val_accuracy: 0.9980 - val_loss: 0.0059
Epoch 44/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9952 - loss: 0.0141 - val_accuracy: 0.9978 - val_loss: 0.0076
Epoch 45/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9941 - loss: 0.0191 - val_accuracy: 0.9951 - val_loss: 0.0162
Epoch 46/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9939 - loss: 0.0185 - val_accuracy: 0.9972 - val_loss: 0.0081
Epoch 47/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9962 - loss: 0.0116 - val_accuracy: 0.9964 - val_loss: 0.0111
Epoch 48/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9878 - loss: 0.0385 - val_accuracy: 0.9654 - val_loss: 0.0858
Epoch 49/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9954 - loss: 0.0128 - val_accuracy: 0.9735 - val_loss: 0.0912
Epoch 50/50
1113/1113 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9936 - loss: 0.0183 - val_accuracy: 0.9966 - val_loss: 0.0104

In [21]:
X_new = df.iloc[10]
X_new = X_new.drop('Chased Successfully')
X_new

Innings Runs                59.000
Target Score               100.000
Wickets left                10.000
CRR                          7.375
Last Five                   44.000
                            ...
Bat Second_New Zealand       0.000
Bat Second_Pakistan          1.000
Bat Second_South Africa      0.000
Bat Second_Sri Lanka         0.000
Bat Second_West Indies       0.000
Name: 10, Length: 104, dtype: float64

In [23]:
model.predict(X_new)

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense" is incompatible with the layer: expected axis -1 of input shape to have value 104, but received input with shape (32, 1)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(32, 1), dtype=float32)
  • training=False
  • mask=None